export const CREATE_REDFLAG_SUCCESS = 'CREATE_REDFLAG_SUCCESS';
export const GET_REDFLAGS_SUCCESS = 'GET_REDFLAGS_SUCCESS';
export const CREATE_REDFLAG_FAILED = 'CREATE_REDFLAG_FAILED';
export const GET_REDFLAGS_FAILED = 'GET_REDFLAGS_FAILED';
